clean:
	docker system prune -f
	docker volume prune -f

up:
	docker compose -f ./docker-compose.yml up

down:
	docker compose -f ./docker-compose.yml down

up-wsl:
	docker compose -f ./docker-compose-wsl.yml up

down-wsl:
	docker compose -f ./docker-compose-wsl.yml down

