dotnet-build:
	dotnet build ./Otel-Backend.sln

dotnet-run-basket-api:
	 dotnet run --project ./Basket.API/Basket.API.csproj

dotnet-run-catalog-api:
	 dotnet run --project ./Catalog.API/Catalog.API.csproj

dotnet-run-service-worker:
	 dotnet run --project ./ServiceWorker/ServiceWorker.csproj	 	 

	 